spring:
  shardingsphere:
    datasource:
      names: db0,db1
      db0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/database_0?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
        username: root
        password: 123456
      db1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/database_1?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
        username: root
        password: 123456
    sharding:
      default-database-strategy:
        inline:
          sharding-column: user_id
          algorithm-expression: db$->{user_id%2}
      tables:
        student:
          actual-data-nodes: db$->{0..1}.student_$->{0..1}
          database-strategy:
            standard:
              sharding-column: id
              precise-algorithm-className: com.example.demo.config.CustomStandardShardingStrategy
              range-algorithm-className: com.example.demo.config.CustomStandardShardingStrategy
            #inline:
             # sharding-column: id
              #algorithm-expression: db$->{id%2}
          table-strategy:
            standard:
              sharding-column: age
              precise-algorithm-className: com.example.demo.config.CustomStandardShardingStrategy
              range-algorithm-className: com.example.demo.config.CustomStandardShardingStrategy
              #inline:
             # sharding-column: age
              #algorithm-expression: student_$->{age%2}
    props:
      sql:
        show: true

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.example.demo.pojo
  type-enums-package: com.example.demo.myenum